version: '3'
services:
    php:
        build: .
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        ports:
            - 8000:80
        container_name: php7.2-original-forum
        depends_on:
            - mysql # DB接続エラーになるためmysqlを先に立ち上げる
    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        platform: linux/x86_64 #Mac M1
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        container_name: mysql5.7-original-forum
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=root
volumes:
    mysql_data: